name: Update Cursor Download Links

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

permissions:
  contents: write

jobs:
  update-links:
    runs-on: ubuntu-latest
    # 设置时区为东八区
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Update lock file
        run: |
          poetry lock

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run update script
        run: |
          poetry run python src/update_cursor_links.py

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md version-history.json poetry.lock
          git commit -m "Update Cursor download links"
          git push